  const translations = {
    ru: {
      logo: 'Хаттер',
      logoSub: 'Дизайнер шарфов',
      donate: 'Поддержать',
      densityTitle: 'Плотность (после ВТО)',
      warning: 'Образец не менее 12×12 см (5×5 in), после ВТО. Измеряйте 10×10 см (4×4 in) в центре.',
      densityHint: 'Для точного расчёта пряжи укажите вес образца и его фактические размеры (не только 10×10 см).',
      toolKnit: 'Спицы',
      toolCrochet: 'Крючок',
      lblStitch: 'Петель в 10 см',
      lblRow: 'Рядов в 10 см',
      rapportTitle: 'Раппорт и симметрия',
      lblRepSt: 'Раппорт (петли)',
      lblRepRow: 'Раппорт (ряды)',
      lblSymSt: 'Симметрия (петли)',
      symHint: '*общая',
      symDesc: '* для начала и конца ряда',
      lblSymRow: 'Симметрия (ряды)',
      lblEdges: 'Кромочные (к наборному краю)',
      edgeHint: '(к наборному краю)',
      edgeDesc: 'не входят в раппорт',
      dimTitle: 'Размеры и направление',
      lblDir: 'Направление вязания',
      dirClassic: 'Классическое (ширина → набор)',
      dirCross: 'Поперечное (длина → набор)',
      lblWidth: 'Ширина',
      lblWidthRep: 'Ширина (в раппортах)',
      lblLength: 'Длина',
      lblLengthRep: 'Длина (в раппортах)',
      yarnTitle: 'Калькулятор пряжи',
      lblSwatch: 'Вес образца',
      lblSwatchW: 'Ширина образца',
      lblSwatchH: 'Высота образца',
      lblSkeinW: 'Вес мотка',
      lblSkeinY: 'Метраж мотка',
      lblSkeinP: 'Цена мотка',
      lblReserve: 'Запас пряжи (%)',
      resultTitle: 'Результат расчета',
      resLabelCastOn: 'Наборный край',
      resLabelRows: 'Ряды',
      resLabelYarn: 'Расход пряжи',
      resLabelPrice: 'Цена',
      printBtnText: 'Печать / PDF'
    },
    us: {
      logo: 'The Hatter',
      logoSub: 'Scarf Studio',
      donate: 'Support',
      densityTitle: 'Gauge (after blocking)',
      warning: 'Swatch at least 5×5 in (12×12 cm), after blocking. Measure 4×4 in (10×10 cm) in the center.',
      densityHint: 'For accurate yarn calculation, enter the swatch weight and its actual dimensions (not just 4×4 in).',
      toolKnit: 'Knit',
      toolCrochet: 'Crochet',
      lblStitch: 'Sts per 4 in',
      lblRow: 'Rows per 4 in',
      rapportTitle: 'Pattern repeat & symmetry',
      lblRepSt: 'Repeat (sts)',
      lblRepRow: 'Repeat (rows)',
      lblSymSt: 'Symmetry (sts)',
      symHint: '*total',
      symDesc: '* for beginning and end',
      lblSymRow: 'Symmetry (rows)',
      lblEdges: 'Edge stitches (to cast-on)',
      edgeHint: '(to cast-on)',
      edgeDesc: 'not part of repeat',
      dimTitle: 'Size & direction',
      lblDir: 'Knitting direction',
      dirClassic: 'Classic (width → cast on)',
      dirCross: 'Crosswise (length → cast on)',
      lblWidth: 'Width',
      lblWidthRep: 'Width (in repeats)',
      lblLength: 'Length',
      lblLengthRep: 'Length (in repeats)',
      yarnTitle: 'Yarn calculator',
      lblSwatch: 'Swatch weight',
      lblSwatchW: 'Swatch width',
      lblSwatchH: 'Swatch height',
      lblSkeinW: 'Skein weight',
      lblSkeinY: 'Skein yardage',
      lblSkeinP: 'Skein price',
      lblReserve: 'Yarn reserve (%)',
      resultTitle: 'Results',
      resLabelCastOn: 'Cast on',
      resLabelRows: 'Rows',
      resLabelYarn: 'Yarn usage',
      resLabelPrice: 'Price',
      printBtnText: 'Print / PDF'
    },
    uk: {
      logo: 'The Hatter',
      logoSub: 'Scarf Studio',
      donate: 'Support',
      densityTitle: 'Tension (after blocking)',
      warning: 'Tension square at least 5×5 in (12×12 cm), after blocking. Measure 4×4 in (10×10 cm) in the centre.',
      densityHint: 'For accurate yarn calculation, enter the tension square weight and its actual dimensions (not just 4×4 in).',
      toolKnit: 'Knit',
      toolCrochet: 'Crochet',
      lblStitch: 'Sts per 4 in',
      lblRow: 'Rows per 4 in',
      rapportTitle: 'Pattern repeat & symmetry',
      lblRepSt: 'Repeat (sts)',
      lblRepRow: 'Repeat (rows)',
      lblSymSt: 'Symmetry (sts)',
      symHint: '*total',
      symDesc: '* for beginning and end',
      lblSymRow: 'Symmetry (rows)',
      lblEdges: 'Edge stitches (to cast-on)',
      edgeHint: '(to cast-on)',
      edgeDesc: 'not part of repeat',
      dimTitle: 'Size & direction',
      lblDir: 'Knitting direction',
      dirClassic: 'Classic (width → cast on)',
      dirCross: 'Crosswise (length → cast on)',
      lblWidth: 'Width',
      lblWidthRep: 'Width (in repeats)',
      lblLength: 'Length',
      lblLengthRep: 'Length (in repeats)',
      yarnTitle: 'Yarn calculator',
      lblSwatch: 'Swatch weight',
      lblSwatchW: 'Swatch width',
      lblSwatchH: 'Swatch height',
      lblSkeinW: 'Skein weight',
      lblSkeinY: 'Skein yardage',
      lblSkeinP: 'Skein price',
      lblReserve: 'Yarn reserve (%)',
      resultTitle: 'Results',
      resLabelCastOn: 'Cast on',
      resLabelRows: 'Rows',
      resLabelYarn: 'Yarn usage',
      resLabelPrice: 'Price',
      printBtnText: 'Print / PDF'
    }
  };
